### ISSUE TITLE
No directory "symbol-llm-v2" !!

### ISSUE THREAD

**Issue by lijiaqijane** [xufangzhi/ENVISIONS#1]
Hi,

I'm failed to run the code in this repo. 

Most main py used the directory "symbol-llm-v2" but i found nowhere in the current version of codes.

Could you fixed the problem and update the code? Many thanks~

**Comment by xufangzhi** [comment]
Hi, thanks for your attention. We will complete the codebase within 1-2 weeks. This issue will be open until we finish it. Please stay tuned !

**Comment by xufangzhi** [comment]
We have fixed this issue in Branch v0.2 ! Please try it !
