### ISSUE TITLE
Some files missed

### ISSUE THREAD

**Issue by Yofuria** [xufangzhi/ENVISIONS#3]
I am very impressed with your work. However, when reproducing the code, I encountered a few questions. I would greatly appreciate your assistance with the following:
1. In Line 84 of self_training.py, you reference a file called label_preference.py, but I cannot find it in your codebase. Has this file been renamed, or is it not actually required?
2. In Line 173 of organize_preference_data_llama2chat.py, you use scores[i][j] where j is a number. However, scores is a list derived from gsm_math_full_v17_llama2chat_part1_iter0.npy, and scores[i] is a dictionary that doesn't have numeric keys. Is there a mistake in how I am reading or using this file?
3. In Lines 81, 104, and 114 of self_training.py, it appears that some training data or configurations might be missing. Could you please confirm if these files are still needed?

Thank you very much for your time and assistance. I look forward to your response!!!

**Comment by xufangzhi** [comment]
Hello, thanks for your support. Some files and directories of our code are not complete. It takes time to make it complete (expected within 1~2 weeks). For the second question, ``scores[i]`` is List type. For the third question, the assertion is required. We will make this issue open until we complete the codebase. Please stay tuned !

**Comment by xufangzhi** [comment]
We have fixed the missing files. Please have a try. Feel free to open the issue, if you have other reproduce problems.
