### ISSUE TITLE
Missing FIles

### ISSUE THREAD

**Issue by suhmily** [xufangzhi/ENVISIONS#5]
When I run python ENVISIONS/self_training.py --base_model "llama2chat" --model_size "7B" --task_prefix "gsm_math_full_llama2chat" --vllm_batchsize 1, I got FileNotFoundError: [Errno 2] No such file or directory: 'ENVISIONS/open-instruct/data/gsm_math_full_part2.json'

**Comment by xufangzhi** [comment]
Hi, thanks for pointing out the issue. We have fixed it. Please have a try. Feel free to open any issue when you reproduce the training.
